<a href="https://colab.research.google.com/github/ismailelbat/BAT/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
2+2

4

In [7]:
5+9
13+99
1+6


7

In [9]:
import torch
import numpy as np


In [14]:
my_list = [[1,2,3,4],[6,7,8,9]]
my_list

[[1, 2, 3, 4], [6, 7, 8, 9]]

In [16]:
np1 = np.random.rand(2,4)
np1

array([[0.52894977, 0.80467026, 0.22212298, 0.36001924],
       [0.02124838, 0.10028516, 0.36662993, 0.82743869]])

In [17]:
np1.dtype

dtype('float64')

In [23]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.3210, 0.2316, 0.4369, 0.2170],
        [0.7660, 0.5975, 0.1898, 0.5006],
        [0.6942, 0.0235, 0.3886, 0.3666]])

In [24]:
tensor_2d.dtype

torch.float32

In [22]:
tensor_3d = torch.zeros(3,2,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])