<a href="https://colab.research.google.com/github/ismailelbat/BAT/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
5+9
13+99
1+6


7

In [ ]:
import torch
import numpy as np


In [ ]:
my_list = [[1,2,3,4],[6,7,8,9]]
my_list

[[1, 2, 3, 4], [6, 7, 8, 9]]

In [ ]:
np1 = np.random.rand(2,4)
np1

array([[0.52894977, 0.80467026, 0.22212298, 0.36001924],
       [0.02124838, 0.10028516, 0.36662993, 0.82743869]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
tensor_np1 = torch.from_numpy(np1)
tensor_np1

tensor([[0.5289, 0.8047, 0.2221, 0.3600],
        [0.0212, 0.1003, 0.3666, 0.8274]], dtype=torch.float64)

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.3210, 0.2316, 0.4369, 0.2170],
        [0.7660, 0.5975, 0.1898, 0.5006],
        [0.6942, 0.0235, 0.3886, 0.3666]])

In [ ]:
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(3,2,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch_2d = torch.arange(20).reshape(5,4)
my_torch_2d

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [37]:
a2 = my_torch.reshape(-1,2)
a2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [49]:
w1= torch.rand(2,5)
w1

tensor([[0.9696, 0.0458, 0.8498, 0.8800, 0.4899],
        [0.6475, 0.3509, 0.0683, 0.5092, 0.5425]])

In [54]:
w2= torch.tensor([[0,2,3,4,5],[2,3,4,5,6]])
w2

tensor([[0, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

In [55]:
torch.add(w1,w2)
w1+w2
torch.div(w1,w2)

tensor([[   inf, 0.0229, 0.2833, 0.2200, 0.0980],
        [0.3237, 0.1170, 0.0171, 0.1018, 0.0904]])